remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
include: ["assets/css/style.css"]

title: "Niels Dutrievoz"
description: "PhD Student in Polar Climate Modeling"

header_image: "images/banner.jpeg"

include:
  - _includes/mathjax.html
