remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

include: ["assets/css/style.css"]

title: "gaojingketizu"
description: "shuitongweisu"

header_image: "images/banner111.jpeg"

include:
  - _includes/mathjax.html



